[module]
  [module.hugoVersion]
    extended = true
    min = '0.90.0'
[params]
  themeColor="yellow"
  showMenuItems = 5
  centerTheme = true
  favicon = "/img/favicon.png"



baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Portfolio'


[[menu.main]]
name = "All Projects"
url = "/"
weight = 1

[[menu.main]]
name = "Game Dev"
url = "/projects/gamedev/"
weight = 2

[[menu.main]]
name = "Technical Art"
url = "/projects/techart/"
weight = 3

[[menu.main]]
name = "UX/HCI"
url = "/projects/uxhci/"
weight = 4

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 999

